# Generated by Django 6.0.3 on 2026-03-18 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(help_text='Número de Identificación Tributaria', max_length=20, unique=True, verbose_name='NIT')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=200, verbose_name='Nombre')),
                ('contacto', models.CharField(blank=True, help_text='Información de contacto (email, teléfono)', max_length=100, verbose_name='Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(db_index=True, help_text='Número único de referencia del certificado', max_length=50, unique=True, verbose_name='Número de Referencia')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del certificado bancario', max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha del certificado bancario', verbose_name='Fecha')),
                ('cliente_nit', models.CharField(db_index=True, help_text='NIT del cliente asociado', max_length=20, verbose_name='NIT Cliente')),
                ('archivo', models.FileField(help_text='Archivo PDF o imagen del certificado', upload_to='certificados/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de actualización del registro', verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente relacionado al certificado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Certificado Bancario',
                'verbose_name_plural': 'Certificados Bancarios',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(db_index=True, help_text='Número único de la factura', max_length=50, unique=True, verbose_name='Número de Factura')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total de la factura', max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(db_index=True, help_text='Fecha de emisión de la factura', verbose_name='Fecha')),
                ('cliente_nit', models.CharField(db_index=True, help_text='NIT del cliente que emite la factura', max_length=20, verbose_name='NIT Cliente')),
                ('archivo', models.FileField(help_text='Archivo PDF o imagen de la factura', upload_to='facturas/', verbose_name='Archivo')),
                ('ocr_data', models.JSONField(blank=True, help_text='Datos extraídos automáticamente mediante OCR', null=True, verbose_name='Datos OCR')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de actualización del registro', verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente relacionado a la factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('contador', 'Contador'), ('admin', 'Administrador')], help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(help_text='Usuario de autenticación de Django', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_match', models.CharField(choices=[('match', 'Coincide'), ('partial', 'Coincide Parcialmente'), ('no_match', 'No Coincide')], help_text='Resultado de la comparación', max_length=20, verbose_name='Estado del Match')),
                ('diferencias', models.TextField(blank=True, default='', help_text='Descripción de las diferencias encontradas', verbose_name='Diferencias')),
                ('resumen', models.TextField(help_text='Resumen del análisis de pago', verbose_name='Resumen')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de actualización del registro', verbose_name='Fecha de Actualización')),
                ('match_score', models.DecimalField(decimal_places=2, default=0, help_text='Puntaje de coincidencia (0-100)', max_digits=5, verbose_name='Puntaje de Match')),
                ('certificado', models.ForeignKey(help_text='Certificado bancario asociado', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='core.certificadobancario', verbose_name='Certificado')),
                ('factura', models.ForeignKey(help_text='Factura asociada', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='core.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('factura', 'certificado'), name='unique_factura_certificado_match')],
            },
        ),
    ]
